import { useState } from 'react';
import { Check, Loader2, Mic, MicOff, RotateCcw, Send, Volume2 } from 'lucide-react';
import type { ConversationMessage } from '@/types';
import { Button, Card } from './ui';
import { AiMark } from './shared';

export function ConversationBubble({ message }: { message: ConversationMessage }) {
  const isPatient = message.type === 'patient';
  return <div className={`flex gap-3 ${isPatient ? 'flex-row-reverse' : ''}`}><div className="mt-1 shrink-0">{isPatient ? <div className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-100 text-sm font-bold text-blue-700">You</div> : <AiMark size="sm" />}</div><div className={`max-w-[82%] ${isPatient ? 'items-end text-right' : ''}`}><div className={`rounded-2xl px-4 py-3 ${isPatient ? 'rounded-tr-sm bg-blue-600 text-white' : 'rounded-tl-sm border border-teal-100 bg-teal-50 text-surface-800 dark:border-teal-900 dark:bg-teal-950/40 dark:text-surface-100'}`}><p className="text-sm leading-relaxed">{message.text}</p></div><div className={`mt-1.5 flex items-center gap-2 text-[11px] text-surface-400 ${isPatient ? 'justify-end' : ''}`}><span>{message.timestamp}</span><span className="capitalize">{message.mode}</span>{!isPatient && <button aria-label="Play question" className="text-teal-600 hover:text-teal-700"><Volume2 className="h-3.5 w-3.5" /></button>}</div></div></div>;
}

export function AudioRecorder({ onSubmit }: { onSubmit: (text: string) => void }) {
  const [mode, setMode] = useState<'idle' | 'listening' | 'processing' | 'confirm'>('idle');
  const [heard] = useState('I have had a headache since yesterday.');
  const start = () => { setMode('listening'); window.setTimeout(() => { setMode('confirm'); }, 1400); };
  const confirm = () => { onSubmit(heard); setMode('idle'); };
  return <Card className="relative overflow-hidden bg-gradient-to-b from-teal-50 to-white text-center dark:from-teal-950/40 dark:to-surface-900" padding="lg"><div className="mx-auto max-w-md">{mode === 'idle' && <><button onClick={start} aria-label="Tap to speak" className="group relative mx-auto mb-5 flex h-24 w-24 items-center justify-center rounded-full bg-teal-700 text-white shadow-lg shadow-teal-700/20 transition-transform hover:scale-105"><Mic className="h-9 w-9" /><span className="absolute inset-0 rounded-full border-2 border-teal-400 opacity-0 transition-opacity group-hover:animate-pulse-ring group-hover:opacity-100" /></button><p className="font-semibold text-surface-800 dark:text-white">Tap to speak</p><p className="mt-1 text-sm text-surface-500">Tell us in your own words</p></>}{mode === 'listening' && <><div className="relative mx-auto mb-5 flex h-24 w-24 items-center justify-center rounded-full bg-error-500 text-white shadow-lg"><MicOff className="h-9 w-9" /><span className="absolute inset-0 animate-pulse-ring rounded-full border-2 border-error-300" /></div><p className="font-semibold text-error-600">Listening...</p><div className="mt-4 flex h-8 items-center justify-center gap-1.5">{[2, 5, 8, 4, 9, 6, 3, 7, 4, 8, 5].map((height, index) => <span key={index} className="w-1 rounded-full bg-teal-500 animate-wave" style={{ height: `${height * 3}px`, animationDelay: `${index * 70}ms` }} />)}</div></>}{mode === 'confirm' && <><div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-full bg-success-100 text-success-600"><Check className="h-8 w-8" /></div><p className="text-xs font-bold uppercase tracking-wider text-surface-400">I heard</p><p className="mt-2 text-lg font-semibold text-surface-800 dark:text-white">“{heard}”</p><div className="mt-5 flex justify-center gap-3"><Button variant="outline" onClick={() => setMode('idle')} icon={<RotateCcw className="h-4 w-4" />}>Try again</Button><Button onClick={confirm} icon={<Check className="h-4 w-4" />}>Confirm</Button></div></>}{mode === 'processing' && <><Loader2 className="mx-auto mb-5 h-14 w-14 animate-spin text-teal-600" /><p className="font-semibold text-surface-800 dark:text-white">Understanding your voice...</p></>}</div></Card>;
}

export function PatientConversationComposer({ onSubmit }: { onSubmit: (text: string) => void }) {
  const [mode, setMode] = useState<'voice' | 'text'>('voice');
  const [text, setText] = useState('');
  return <div>{<div className="mb-4 flex justify-center"><div className="inline-flex rounded-xl bg-surface-100 p-1 dark:bg-surface-800"><button className={`rounded-lg px-4 py-2 text-xs font-semibold transition-colors ${mode === 'voice' ? 'bg-white text-teal-700 shadow-sm dark:bg-surface-700 dark:text-teal-300' : 'text-surface-500'}`} onClick={() => setMode('voice')}><Mic className="mr-1.5 inline h-3.5 w-3.5" />Voice</button><button className={`rounded-lg px-4 py-2 text-xs font-semibold transition-colors ${mode === 'text' ? 'bg-white text-teal-700 shadow-sm dark:bg-surface-700 dark:text-teal-300' : 'text-surface-500'}`} onClick={() => setMode('text')}><Send className="mr-1.5 inline h-3.5 w-3.5" />Text</button></div></div>}{mode === 'voice' ? <AudioRecorder onSubmit={onSubmit} /> : <div className="flex gap-2"><input autoFocus value={text} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && text.trim()) { onSubmit(text); setText(''); } }} placeholder="Type your answer..." className="flex-1 rounded-xl border border-surface-200 bg-white px-4 py-3 text-sm outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100 dark:border-surface-700 dark:bg-surface-900 dark:text-white" /><Button aria-label="Send answer" onClick={() => { if (text.trim()) { onSubmit(text); setText(''); } }} icon={<Send className="h-4 w-4" />} /></div>}</div>;
}
