import { HeartPulse, ShieldCheck, Sparkles, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';

export function Logo({ compact = false, light = false, linkTo = '/' }: { compact?: boolean; light?: boolean; linkTo?: string }) {
  return <Link to={linkTo} className="group inline-flex items-center gap-2.5" aria-label="MediKiosk home"><div className="relative flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-teal-700 text-white shadow-sm transition-transform duration-200 group-hover:scale-105"><HeartPulse className="h-5 w-5" strokeWidth={2.4} /><span className="absolute -right-0.5 -top-0.5 h-2 w-2 rounded-full bg-teal-300" /></div>{!compact && <span className={`font-jakarta text-lg font-bold tracking-tight ${light ? 'text-white' : 'text-surface-900 dark:text-white'}`}>Medi<span className="text-teal-600">Kiosk</span></span>}</Link>;
}

export function TrustPill({ children, icon = <ShieldCheck className="h-3.5 w-3.5" /> }: { children: React.ReactNode; icon?: React.ReactNode }) { return <span className="inline-flex items-center gap-1.5 rounded-full border border-teal-100 bg-teal-50 px-3 py-1.5 text-xs font-semibold text-teal-700 dark:border-teal-900 dark:bg-teal-950/50 dark:text-teal-300">{icon}{children}</span>; }

export function AiMark({ size = 'md' }: { size?: 'sm' | 'md' | 'lg' }) { const sizes = { sm: 'h-7 w-7', md: 'h-9 w-9', lg: 'h-12 w-12' }; return <div className={`flex ${sizes[size]} items-center justify-center rounded-xl bg-teal-100 text-teal-700 dark:bg-teal-900/60 dark:text-teal-300`}><Sparkles className={size === 'lg' ? 'h-6 w-6' : 'h-4 w-4'} /></div>; }

export function PatientAvatar({ name, size = 'md', className = '' }: { name: string; size?: 'sm' | 'md' | 'lg' | 'xl'; className?: string }) { const sizes = { sm: 'h-8 w-8 text-xs', md: 'h-10 w-10 text-sm', lg: 'h-14 w-14 text-lg', xl: 'h-20 w-20 text-2xl' }; const colors = ['bg-teal-100 text-teal-700', 'bg-blue-100 text-blue-700', 'bg-amber-100 text-amber-700', 'bg-rose-100 text-rose-700']; const color = colors[name.charCodeAt(0) % colors.length]; return <div className={`flex shrink-0 items-center justify-center rounded-full font-bold ${sizes[size]} ${color} ${className}`}>{name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</div>; }

export function OfflineStatus({ status = 'synced' }: { status?: 'offline' | 'pending' | 'syncing' | 'synced' | 'failed' }) { const config = { offline: { label: 'Offline mode', dot: 'bg-warning-500', className: 'text-warning-700 bg-warning-50 border-warning-100' }, pending: { label: 'Pending sync', dot: 'bg-warning-500', className: 'text-warning-700 bg-warning-50 border-warning-100' }, syncing: { label: 'Syncing...', dot: 'bg-blue-500 animate-pulse', className: 'text-blue-700 bg-blue-50 border-blue-100' }, synced: { label: 'Synced', dot: 'bg-success-500', className: 'text-success-700 bg-success-50 border-success-100' }, failed: { label: 'Sync failed', dot: 'bg-error-500', className: 'text-error-700 bg-error-50 border-error-100' } }; const item = config[status]; return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] font-semibold ${item.className}`}><span className={`h-1.5 w-1.5 rounded-full ${item.dot}`} />{item.label}</span>; }

export function PrivacyNote({ children = 'Your information is securely handled.' }: { children?: React.ReactNode }) { return <div className="flex items-center gap-2 text-xs text-surface-500"><ShieldCheck className="h-4 w-4 text-teal-600" />{children}</div>; }

export function PatientWelcomeMark() { return <div className="relative mx-auto mb-8 flex h-28 w-28 items-center justify-center rounded-[2rem] bg-teal-50 shadow-soft dark:bg-teal-950/40"><div className="flex h-20 w-20 items-center justify-center rounded-3xl bg-teal-700 text-white shadow-lg"><UserRound className="h-10 w-10" strokeWidth={1.7} /></div><div className="absolute -right-2 -top-2 flex h-10 w-10 items-center justify-center rounded-xl bg-white text-teal-700 shadow-card dark:bg-surface-800"><HeartPulse className="h-5 w-5" /></div></div>; }
